export const CAROUSEL_BANNER_WIDTH = 1024;
export const CAROUSEL_BANNER_HEIGHT = 320;
export const CAROUSEL_BANNER_ASPECT_RATIO = CAROUSEL_BANNER_WIDTH / CAROUSEL_BANNER_HEIGHT;
export const CAROUSEL_BANNER_SIZE_LABEL = `${CAROUSEL_BANNER_WIDTH} × ${CAROUSEL_BANNER_HEIGHT} px (3.2:1 aspect ratio)`;
