export const DEFAULT_ANNOUNCEMENT_MESSAGES = [
  "💵 CASH ON DELIVERY — PAY AT YOUR DOORSTEP, ZERO RISK",
  "🥭 FRESH EXPORT-QUALITY MANGOES — ORDER NOW",
  "🏦 DIRECT BANK TRANSFER AVAILABLE — UPLOAD YOUR RECEIPT AFTER PAYMENT",
] as const;
